image: docker:stable

services:
- docker:dind 

before_script:
- docker info

build-docker:
    stage: build
    script: 
    - docker build -t minha-imagem .

#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    