image: docker:stable

cache:
  key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .yarn-cache/
    - Dockerfile

variables:
  DOCKER_IMAGE_NAME: cypress-enjoeat
  DOCKER_IMAGE_TAG: 1.0

build-docker:
  stage: build
  script: 
    -  docker build --cache-from $DOCKER_IMAGE_NAME -t $DOCKER_IMAGE_NAME .

test-docker:
  stage: test
  script: 
    - docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG npm run test
